version: "3.8"
services:
  nginx:
    image: securityonion/so-nginx:2.3.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      
  Spidertrap:
    image : ubuntu:latest
    ports:
      - 8000:8000
